version: '3'

services:

    phpfpm:
        container_name: exp-php
        image: exp-php
        build:
            context: ./docker-files/dev/php
        env_file:
            - .env.local
        user: "1000:1000"
        volumes:
            - .:/app
            - ./.data/tmp:/tmp

    nginx:
        container_name: exp-nginx
        image: exp-nginx
        build:
            context: docker-files/dev/nginx
        env_file:
            - .env.local
        ports:
            - 80:80
        depends_on:
            - phpfpm
        volumes:
            - .:/app